# Generated by Django 4.0.5 on 2022-07-12 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0006_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='uploadedFile',
            field=models.FileField(upload_to=''),
        ),
    ]
