# Generated by Django 4.0.5 on 2022-07-12 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0007_alter_document_uploadedfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stockname_stocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stockname', models.CharField(max_length=50)),
                ('stockcode', models.CharField(max_length=50)),
            ],
        ),
    ]
